### ISSUE TITLE
Scan for devices not working

### ISSUE THREAD

**Issue by DaireNiC** [lorenzoromagnoli/Ionic2_arduino_BLE_test#1]
I cloned the app exactly and ran npm install. Built for android with no problems. Uploaded to s7 and installed but the scan for devices functionality does not work.  I have multiple bluetooth devices on and ready but they do not show up.  Am I missing something?

**Comment by lorenzoromagnoli** [comment]
Have you tried debugging the app with Chrome?
Do you get errors in the js console?

**Comment by DaireNiC** [comment]
I have. Just one error. The logs only show that it isn't connected to a native device.

 Native: tried calling BLE.enable, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator. 

Also - thanks a bunch for uploading your code. The docs for BLE and ionic 2 are super vague. This is really helpful!

**Comment by lorenzoromagnoli** [comment]
Check out this guide to understand how to debug your app running on Android within Chrome 
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews
